### PR TITLE
Add poetry project file

### PR DESCRIPTION
**Pull request by alexagv**
https://python-poetry.org/
As more developers might join this project I do think it's time to add a dependency/package management. Another alternative is Pipenv, however that one really struggles with package sub dependencies often leading to conflicts it cant handle. 

Poetry however worked out rather well. I tried initially to use a regular requirments.txt setup. However, that's not possible due to NumPy needing to be installed first and "regular" pip install with requirments.txt do not execute in sequential order.

I'll leave it as an open PR, then you can decide if you want to use it or not.

### CODE REVIEW

**Comment by soukron** [comment]
Never heard about poetry but having proper instructions to set a development environment are a nice addition.

**Comment by ElvinC** [comment]
It does look pretty neat. I'll have a bunch of time in a week to work on the project + cleaning up the code a bit so I'll have a try then.

**Comment by alexagv** [comment]
@ElvinC, I tested this on Mac, Windows 10 and now recently Ubuntu 20. 
One common issue is qt dependencies, something changed in OpenCV, so locking the opencv version to 4.1.2.30 might help the ease of setup, related post here:
https://stackoverflow.com/a/60153609

**Comment by ElvinC** [comment]
Hmm that's strange. Which systems had that issue?

**Comment by alexagv** [comment]
> Hmm that's strange. Which systems had that issue?

Ubuntu 20.04

**Comment by ElvinC** [comment]
Alright, thanks

**Pull request merged**
