### PR TITLE
Add HW acceleration for video encoding

### PR DESCRIPTION
**Pull request by alexagv**
I'll add this is a draft as its just a quick test from my end testing HW acceleration on Mac, Windows and Linux should also be supported, however it depends on the FFmpeg installation on the users computer.

Using "WriteGear" instead of cv2.videowriter is quite similar however it enables you to add advanced FFmpeg commands such as harware encoder etc.

I disabled the preview for now to check the speed, however I guess adding a checkbox in the GUI later for "enable HW acceleration" and setting bitrate (currently hardcoded to 20Mbit/s) etc would be something nice to have later.

If I get some time later this week I might have a look at Windows and HW acceleration there as well.

### CODE REVIEW

**Comment by alexagv** [comment]
As for VidGear they have a rather nice readme, relevant info here:
https://abhitronix.github.io/vidgear/gears/writegear/compression/usage/
https://abhitronix.github.io/vidgear/latest/gears/writegear/compression/advanced/ffmpeg_install/

**Comment by ElvinC** [comment]
That's pretty cool, thanks for helping out. Haven't tried this draft pull request thing before, so I guess you just let me know if it's ready to be merged?

**Comment by alexagv** [comment]
> That's pretty cool, thanks for helping out. Haven't tried this draft pull request thing before, so I guess you just let me know if it's ready to be merged?

Yeah, will let you know 👍 Will do some testing for Windows with Nvidia GPU encoding etc during the week.

**Comment by alexagv** [comment]
So in order to achieve fixed bitrate on export i used an old trick called "constrained encoding", basically tells FFMpeg to encode "lossless" then you limit bitrate ish to the desired value. This was to overcome how vidgear has implemented their libx264 encoder with "crf" aka variable bitrate constant quality as their default (even though you specify cbr...).
Only one new dependency, VidGear (pip install vidgear). However, I really do think we should continue using a package manager ala Pipenv or Poetry. I used Poetry now for testing across multiple machines and its way better than Pipenv, which I use at work ...
Will add another PR for that then you can see if you like it or not.

**Comment by alexagv** [comment]
And HW acceleartion on Linux is not yet tested

**Pull request merged**
